-- Corrige o `uf` dos registros de pontos_recarga já sincronizados: a Open Charge Map
-- devolve `StateOrProvince` sem padrão nenhum (sigla, nome completo com/sem acento em
-- qualquer capitalização, nome em inglês, nome de região metropolitana, "cidade - UF",
-- ou até só o nome da cidade sem nenhuma pista de estado).
--
-- Mapeamento levantado em 2026-08-08 via `select distinct uf, count(*) from pontos_recarga
-- group by uf` — cobre exaustivamente os 807 registros não-nulos existentes na época
-- (os outros 800 já são `uf is null`, sem endereço suficiente na fonte). A partir de agora
-- a Edge Function `sync-ocm` já normaliza na origem (ver normalizarUf em
-- supabase/functions/sync-ocm/index.ts) — esta migration só corrige o que já estava gravado.
update pontos_recarga pr
set uf = mapa.sigla
from (values
  ('São Paulo', 'SP'),
  ('Ceará', 'CE'),
  ('Rio Grande do Sul', 'RS'),
  ('Paraná', 'PR'),
  ('Bahia', 'BA'),
  ('Goiás', 'GO'),
  ('Minas Gerais', 'MG'),
  ('Santa Catarina', 'SC'),
  ('Rio de Janeiro', 'RJ'),
  ('Rio Grande do Norte', 'RN'),
  ('Maranhão', 'MA'),
  ('Piauí', 'PI'),
  ('Paraíba', 'PB'),
  ('Pernambuco', 'PE'),
  ('Espírito Santo', 'ES'),
  ('Alagoas', 'AL'),
  ('Distrito Federal', 'DF'),
  ('Pará', 'PA'),
  ('Sergipe', 'SE'),
  ('Sao Paulo', 'SP'),
  ('Minas Gerais ', 'MG'),
  ('Tocantins', 'TO'),
  ('Ceara', 'CE'),
  ('Too de Janeiro', 'RJ'),
  ('bahia', 'BA'),
  ('Espirito Santo', 'ES'),
  ('São Paulo ', 'SP'),
  ('Rio de Janeiro ', 'RJ'),
  ('Parana', 'PR'),
  ('paraná', 'PR'),
  ('Amazonas', 'AM'),
  ('Piaui', 'PI'),
  ('Mato Grosso', 'MT'),
  ('Bahia ', 'BA'),
  ('Santa Catarina ', 'SC'),
  ('Goiás ', 'GO'),
  ('Região Metropolitana de São Paulo', 'SP'),
  ('CEARA', 'CE'),
  ('Río Grande do Sul', 'RS'),
  ('Federal District', 'DF'),
  ('Mato Grosso do Sul', 'MS'),
  ('rio grande do sul', 'RS'),
  ('minas gerais', 'MG'),
  ('ceará', 'CE'),
  ('Região Metropolitana de Campina Grande', 'PB'),
  ('Rio Grande Do Sul', 'RS'),
  (' Distrito Federal', 'DF'),
  ('São paulo', 'SP'),
  ('mg', 'MG'),
  ('paraiba', 'PB'),
  ('tocantins', 'TO'),
  ('CORRENTE/PI', 'PI'),
  ('Sp', 'SP'),
  ('Goias', 'GO'),
  ('Ceara ', 'CE'),
  ('brasileia', 'AC'),
  ('Rio Grande del sur', 'RS'),
  ('santa catarina ', 'SC'),
  ('goias ', 'GO'),
  ('Região Metropolitana de Guarabira', 'PB'),
  ('Barreiras - BA', 'BA'),
  ('Rio Grande do Sul ', 'RS'),
  (' GO', 'GO'),
  ('MINAS GERAIS', 'MG'),
  ('Camocim', 'CE'),
  ('CEARÁ', 'CE'),
  ('Indaiatuba - SP', 'SP'),
  ('parana', 'PR'),
  ('PIAUI', 'PI'),
  (' Bahia', 'BA'),
  ('goias', 'GO'),
  ('Metropolitan Region of Porto Alegre', 'RS')
) as mapa(bruto, sigla)
where pr.uf = mapa.bruto;
